// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/vault/v1beta1/deposit.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Deposit struct {
	VaultID         uint64                                 `protobuf:"varint,1,opt,name=vaultID,proto3" json:"vaultID,omitempty" yaml:"VaultID"`
	Depositor       string                                 `protobuf:"bytes,2,opt,name=depositor,proto3" json:"depositor,omitempty" yaml:"depositor"`
	AmountDeposited github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=amount_deposited,json=amountDeposited,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount_deposited" yaml:"amount_deposited"`
}

func (m *Deposit) Reset()         { *m = Deposit{} }
func (m *Deposit) String() string { return proto.CompactTextString(m) }
func (*Deposit) ProtoMessage()    {}
func (*Deposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_513dc25d9c6a85e8, []int{0}
}
func (m *Deposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Deposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Deposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Deposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deposit.Merge(m, src)
}
func (m *Deposit) XXX_Size() int {
	return m.Size()
}
func (m *Deposit) XXX_DiscardUnknown() {
	xxx_messageInfo_Deposit.DiscardUnknown(m)
}

var xxx_messageInfo_Deposit proto.InternalMessageInfo

type Deposits struct {
	Deposits   []Deposit           `protobuf:"bytes,1,rep,name=deposits,proto3" json:"deposits" yaml:"Deposits"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty" yaml:"pagination"`
}

func (m *Deposits) Reset()         { *m = Deposits{} }
func (m *Deposits) String() string { return proto.CompactTextString(m) }
func (*Deposits) ProtoMessage()    {}
func (*Deposits) Descriptor() ([]byte, []int) {
	return fileDescriptor_513dc25d9c6a85e8, []int{1}
}
func (m *Deposits) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Deposits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Deposits.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Deposits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deposits.Merge(m, src)
}
func (m *Deposits) XXX_Size() int {
	return m.Size()
}
func (m *Deposits) XXX_DiscardUnknown() {
	xxx_messageInfo_Deposits.DiscardUnknown(m)
}

var xxx_messageInfo_Deposits proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Deposit)(nil), "comdex.vault.v1beta1.Deposit")
	proto.RegisterType((*Deposits)(nil), "comdex.vault.v1beta1.Deposits")
}

func init() {
	proto.RegisterFile("comdex/vault/v1beta1/deposit.proto", fileDescriptor_513dc25d9c6a85e8)
}

var fileDescriptor_513dc25d9c6a85e8 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0xc7, 0x63, 0x86, 0xe8, 0xe6, 0x49, 0x6c, 0x44, 0x45, 0x54, 0x93, 0x66, 0x57, 0x46, 0x82,
	0x0a, 0x69, 0xb6, 0x56, 0x0e, 0x48, 0x1c, 0xa3, 0x5e, 0x7a, 0x83, 0x1c, 0x38, 0x70, 0x18, 0x72,
	0x13, 0x2f, 0x44, 0x34, 0x71, 0xa8, 0x9d, 0x89, 0xbe, 0x05, 0x8f, 0xc1, 0xa3, 0x54, 0x9c, 0x76,
	0x44, 0x1c, 0x2c, 0x48, 0xaf, 0x9c, 0xf2, 0x04, 0x28, 0xb6, 0x9b, 0x02, 0xe2, 0x94, 0xf8, 0xef,
	0x9f, 0xff, 0x9f, 0xbf, 0xbf, 0x3f, 0x48, 0x12, 0x59, 0xa4, 0xe2, 0x13, 0xbb, 0xe1, 0xf5, 0x52,
	0xb3, 0x9b, 0xcb, 0x85, 0xd0, 0xfc, 0x92, 0xa5, 0xa2, 0x92, 0x2a, 0xd7, 0xb4, 0x5a, 0x49, 0x2d,
	0xc3, 0xa1, 0x63, 0xa8, 0x65, 0xa8, 0x67, 0xce, 0x86, 0x99, 0xcc, 0xa4, 0x05, 0x58, 0xf7, 0xe7,
	0xd8, 0xb3, 0x67, 0x89, 0x54, 0x85, 0x54, 0x6c, 0xc1, 0x95, 0x60, 0x1f, 0x6b, 0xb1, 0x5a, 0xf7,
	0xa6, 0x15, 0xcf, 0xf2, 0x92, 0xeb, 0x5c, 0x96, 0x8e, 0x25, 0xbf, 0x00, 0x1c, 0xcc, 0x5c, 0xa5,
	0xf0, 0x05, 0x1c, 0x58, 0xfb, 0xf9, 0x6c, 0x04, 0xc6, 0x60, 0x72, 0x37, 0x3a, 0x6f, 0x0c, 0x1e,
	0xbc, 0x71, 0x52, 0x6b, 0xf0, 0xfd, 0x35, 0x2f, 0x96, 0x2f, 0x89, 0x17, 0x48, 0xbc, 0xa3, 0xc3,
	0x29, 0x3c, 0xf2, 0xb7, 0x95, 0xab, 0xd1, 0x9d, 0x31, 0x98, 0x1c, 0x45, 0xc3, 0xd6, 0xe0, 0x53,
	0xc7, 0xf7, 0x5b, 0x24, 0xde, 0x63, 0xa1, 0x86, 0xa7, 0xbc, 0x90, 0x75, 0xa9, 0xdf, 0x79, 0x4d,
	0xa4, 0xa3, 0x03, 0x7b, 0x74, 0xbe, 0x31, 0x38, 0xf8, 0x6e, 0xf0, 0x93, 0x2c, 0xd7, 0xef, 0xeb,
	0x05, 0x4d, 0x64, 0xc1, 0x7c, 0x47, 0xee, 0x73, 0xa1, 0xd2, 0x0f, 0x4c, 0xaf, 0x2b, 0xa1, 0xe8,
	0xbc, 0xd4, 0xad, 0xc1, 0x8f, 0x5c, 0xa1, 0x7f, 0xfd, 0x48, 0x7c, 0xe2, 0xa4, 0x59, 0xaf, 0x7c,
	0x05, 0xf0, 0xd0, 0xaf, 0x54, 0x78, 0x05, 0x0f, 0x3d, 0xab, 0x46, 0x60, 0x7c, 0x30, 0x39, 0x9e,
	0x9e, 0xd3, 0xff, 0xc5, 0x4c, 0xfd, 0x89, 0xe8, 0x71, 0x77, 0xb3, 0xc6, 0xe0, 0xde, 0xa2, 0x35,
	0xf8, 0xc4, 0xd5, 0xde, 0x29, 0x24, 0xee, 0x3d, 0xc3, 0x2b, 0x08, 0xf7, 0x79, 0xdb, 0x5c, 0x8e,
	0xa7, 0x4f, 0xa9, 0xeb, 0x81, 0x76, 0x8f, 0x43, 0xed, 0xe3, 0xf4, 0x65, 0x5e, 0xf1, 0x4c, 0xc4,
	0x42, 0x55, 0xb2, 0x54, 0x22, 0x7a, 0xd8, 0x1a, 0xfc, 0xc0, 0x79, 0xef, 0x4d, 0x48, 0xfc, 0x87,
	0x63, 0xf4, 0x7a, 0xf3, 0x13, 0x05, 0x5f, 0x1a, 0x14, 0x6c, 0x1a, 0x04, 0x6e, 0x1b, 0x04, 0x7e,
	0x34, 0x08, 0x7c, 0xde, 0xa2, 0xe0, 0x76, 0x8b, 0x82, 0x6f, 0x5b, 0x14, 0xbc, 0x65, 0x7f, 0x45,
	0xd8, 0x75, 0x76, 0x21, 0xaf, 0xaf, 0xf3, 0x24, 0xe7, 0x4b, 0xbf, 0x66, 0xbb, 0xb1, 0xb3, 0x79,
	0x2e, 0xee, 0xd9, 0xa9, 0x78, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xce, 0xcb, 0x8f, 0x42, 0x93,
	0x02, 0x00, 0x00,
}

func (m *Deposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Deposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Deposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AmountDeposited.Size()
		i -= size
		if _, err := m.AmountDeposited.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDeposit(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Depositor) > 0 {
		i -= len(m.Depositor)
		copy(dAtA[i:], m.Depositor)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.Depositor)))
		i--
		dAtA[i] = 0x12
	}
	if m.VaultID != 0 {
		i = encodeVarintDeposit(dAtA, i, uint64(m.VaultID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Deposits) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Deposits) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Deposits) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDeposit(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Deposits) > 0 {
		for iNdEx := len(m.Deposits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Deposits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDeposit(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintDeposit(dAtA []byte, offset int, v uint64) int {
	offset -= sovDeposit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Deposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VaultID != 0 {
		n += 1 + sovDeposit(uint64(m.VaultID))
	}
	l = len(m.Depositor)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	l = m.AmountDeposited.Size()
	n += 1 + l + sovDeposit(uint64(l))
	return n
}

func (m *Deposits) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Deposits) > 0 {
		for _, e := range m.Deposits {
			l = e.Size()
			n += 1 + l + sovDeposit(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovDeposit(uint64(l))
	}
	return n
}

func sovDeposit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDeposit(x uint64) (n int) {
	return sovDeposit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Deposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Deposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Deposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultID", wireType)
			}
			m.VaultID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VaultID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depositor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountDeposited", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountDeposited.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeposit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeposit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Deposits) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Deposits: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Deposits: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deposits = append(m.Deposits, Deposit{})
			if err := m.Deposits[len(m.Deposits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDeposit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeposit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDeposit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDeposit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDeposit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDeposit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDeposit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeposit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeposit = fmt.Errorf("proto: unexpected end of group")
)
